'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class WinFormStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iCopy.WinFormStrings", GetType(WinFormStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Donate using PayPal.
        '''</summary>
        Friend Shared ReadOnly Property AboutBox_Donate() As String
            Get
                Return ResourceManager.GetString("AboutBox_Donate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This program is distributed under the terms of GNU GPL License..
        '''</summary>
        Friend Shared ReadOnly Property AboutBox_Label1() As String
            Get
                Return ResourceManager.GetString("AboutBox_Label1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Combine your scanner and printer into a powerful photocopier..
        '''</summary>
        Friend Shared ReadOnly Property AboutBox_lblDescription() As String
            Get
                Return ResourceManager.GetString("AboutBox_lblDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click here to read license text.
        '''</summary>
        Friend Shared ReadOnly Property AboutBox_LinkLabel3() As String
            Get
                Return ResourceManager.GetString("AboutBox_LinkLabel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &gt; icopy.exe [/copy /file /multiplePages ..] [params]
        '''
        '''[params] are the parameters to be used. If a parameter is not specified, iCopy uses the values stored in settings
        '''
        '''/copy /c				Directly copy from scanner to printer, using settings provided or default settings
        '''/file /ScanToFile /f			Scan to a file. If file path is not provided a dialog will let you choose where to save the acquired image
        '''/copyMultiplePages			Scan a multipage document. Also /copymultiplepages
        '''/pdf				Scans to PDF. Output path can b [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Console_Help() As String
            Get
                Return ResourceManager.GetString("Console_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scan More Pages.
        '''</summary>
        Friend Shared ReadOnly Property dlgScanMorePages() As String
            Get
                Return ResourceManager.GetString("dlgScanMorePages", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Another Page.
        '''</summary>
        Friend Shared ReadOnly Property dlgScanMorePages_btnAddPage() As String
            Get
                Return ResourceManager.GetString("dlgScanMorePages_btnAddPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scans another page with the current settings.
        '''</summary>
        Friend Shared ReadOnly Property dlgScanMorePages_btnAddPageToolTip() As String
            Get
                Return ResourceManager.GetString("dlgScanMorePages_btnAddPageToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Process Pages.
        '''</summary>
        Friend Shared ReadOnly Property dlgScanMorePages_btnPrint() As String
            Get
                Return ResourceManager.GetString("dlgScanMorePages_btnPrint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Process the acquired images.
        '''</summary>
        Friend Shared ReadOnly Property dlgScanMorePages_btnPrintToolTip() As String
            Get
                Return ResourceManager.GetString("dlgScanMorePages_btnPrintToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose if you want to add more pages or if you want to process the acquired pages..
        '''</summary>
        Friend Shared ReadOnly Property dlgScanMorePages_Label1() As String
            Get
                Return ResourceManager.GetString("dlgScanMorePages_Label1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Acquired pages:.
        '''</summary>
        Friend Shared ReadOnly Property dlgScanMorePages_lblAcquiredPagesNText() As String
            Get
                Return ResourceManager.GetString("dlgScanMorePages_lblAcquiredPagesNText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Image Settings.
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings() As String
            Get
                Return ResourceManager.GetString("frmImageSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default.
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_btnDefault() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_btnDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sets image settings to their default values.
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_btnDefaultToolTip() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_btnDefaultToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select scanner resolution in DPI (dots per inch) higher values
        '''correspond to higher quality, but also longer acquisition time.
        '''Setting more than 1000 DPI will require a lot of extra time..
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_cboResolutionToolTip() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_cboResolutionToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Center image.
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_chkCenter() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_chkCenter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If checked, iCopy prints the image in the center of the page, otherwise the image will be printed from the upper left corner..
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_chkCenterToolTip() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_chkCenterToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Brightness.
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_lblBrightness() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_lblBrightness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JPEG Quality.
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_lblCompressionLabel() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_lblCompressionLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sets the Compression factor when saving to JPEG image using the Scan to Image function. The higher the value, the better the quality and the bigger the file size..
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_lblCompressionLabelToolTip() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_lblCompressionLabelToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contrast.
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_lblContrast() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_lblContrast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DPI.
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_lblDPI() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_lblDPI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %.
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_lblPerc() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_lblPerc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resolution.
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_lblResolution() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_lblResolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scaling.
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_lblScaling() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_lblScaling", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set brightness value..
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_tbBrightnessToolTip() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_tbBrightnessToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set JPEG compression (Save to File only).
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_tbCompressionToolTip() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_tbCompressionToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set contrast value..
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_tbContrastToolTip() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_tbContrastToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scale the image to the selected percentage.
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_tbScalingToolTip() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_tbScalingToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set brightness value. Enter a value between -100 (darkest) and 100 (brightest).
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_txtBrightnessToolTip() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_txtBrightnessToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set contrast value.  Enter a value from -100 (darker) to 100 (brighter).
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_txtContrastToolTip() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_txtContrastToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter the scaling percentage. Value must be between 1 and 200.
        '''</summary>
        Friend Shared ReadOnly Property frmImageSettings_txtScalingToolTip() As String
            Get
                Return ResourceManager.GetString("frmImageSettings_txtScalingToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start copy process (CTRL+S).
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_btnCopyToolTip() As String
            Get
                Return ResourceManager.GetString("mainFrm_btnCopyToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Image Settings &gt;&gt;.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_btnImageSettings() As String
            Get
                Return ResourceManager.GetString("mainFrm_btnImageSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Image Settings &lt;&lt;.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_btnImageSettingsHide() As String
            Get
                Return ResourceManager.GetString("mainFrm_btnImageSettingsHide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shows/Hides advanced image settings, which include
        '''Brightness, Contrast, Quality and Scaling (CTRL+I).
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_btnImageSettingsToolTip() As String
            Get
                Return ResourceManager.GetString("mainFrm_btnImageSettingsToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Printer settings....
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_btnPrintSetup() As String
            Get
                Return ResourceManager.GetString("mainFrm_btnPrintSetup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change printer and printing options.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_btnPrintSetupToolTip() As String
            Get
                Return ResourceManager.GetString("mainFrm_btnPrintSetupToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Other Scan Modes.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_btnScanModes() As String
            Get
                Return ResourceManager.GetString("mainFrm_btnScanModes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shows other scan modes.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_btnScanModesToolTip() As String
            Get
                Return ResourceManager.GetString("mainFrm_btnScanModesToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose &amp;scanner....
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_btnSelScanner() As String
            Get
                Return ResourceManager.GetString("mainFrm_btnSelScanner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shows a dialog to choose a different scanner.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_btnSelScannerToolTip() As String
            Get
                Return ResourceManager.GetString("mainFrm_btnSelScannerToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Settings.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_btnSettings() As String
            Get
                Return ResourceManager.GetString("mainFrm_btnSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Colors.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_cboPrintModeItem0() As String
            Get
                Return ResourceManager.GetString("mainFrm_cboPrintModeItem0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Black &amp; White.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_cboPrintModeItem1() As String
            Get
                Return ResourceManager.GetString("mainFrm_cboPrintModeItem1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set printing method.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_cboPrintModeToolTip() As String
            Get
                Return ResourceManager.GetString("mainFrm_cboPrintModeToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Colors.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_cboScanModeItem0() As String
            Get
                Return ResourceManager.GetString("mainFrm_cboScanModeItem0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Grayscale.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_cboScanModeItem1() As String
            Get
                Return ResourceManager.GetString("mainFrm_cboScanModeItem1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_cboScanModeItem2() As String
            Get
                Return ResourceManager.GetString("mainFrm_cboScanModeItem2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose the scanning method: 
        '''COLORS - Acquired image will be full-color, printing mode will be set to color automatically
        '''GRAYSCALE - Acquired image will be in grayscale. Scan will be faster. Printer automatically set to Black &amp; White
        '''TEXT - Acquired image will be black &amp; white. This is the fasted method, useful for text, books and copies.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_cboScanModeToolTip() As String
            Get
                Return ResourceManager.GetString("mainFrm_cboScanModeToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use Document Feeder (ADF).
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_chkADF() As String
            Get
                Return ResourceManager.GetString("mainFrm_chkADF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Acquire the pages using the Automatic Document Feeder..
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_chkADFToolTip() As String
            Get
                Return ResourceManager.GetString("mainFrm_chkADFToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duplex acquisition.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_chkDuplex() As String
            Get
                Return ResourceManager.GetString("mainFrm_chkDuplex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Used with ADF, tells the scanner to use duplex acquisition.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_chkDuplexToolTip() As String
            Get
                Return ResourceManager.GetString("mainFrm_chkDuplexToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MULTIPAGE ACQUISITION (CTRL + M)
        '''iCopy will wait for the user to change the page on the flatbed (or ADF) to start another acquisition.
        '''You can scan several page at a time and print them all together or save them in a single PDF file..
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_chkMultipageToolTip() As String
            Get
                Return ResourceManager.GetString("mainFrm_chkMultipageToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save the output to PDF (CTRL +P).
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_chkPDFToolTip() As String
            Get
                Return ResourceManager.GetString("mainFrm_chkPDFToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preview.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_chkPreview() As String
            Get
                Return ResourceManager.GetString("mainFrm_chkPreview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shows a dialog to select the area to be scanned.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_chkPreviewToolTip() As String
            Get
                Return ResourceManager.GetString("mainFrm_chkPreviewToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save the image to a file (CTRL + F).
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_chkSaveToFileToolTip() As String
            Get
                Return ResourceManager.GetString("mainFrm_chkSaveToFileToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to N° of copies.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_lblCopies() As String
            Get
                Return ResourceManager.GetString("mainFrm_lblCopies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paper Size.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_lblPaperSize() As String
            Get
                Return ResourceManager.GetString("mainFrm_lblPaperSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Printer.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_lblPrinter() As String
            Get
                Return ResourceManager.GetString("mainFrm_lblPrinter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scanner.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_lblScanner() As String
            Get
                Return ResourceManager.GetString("mainFrm_lblScanner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About iCopy.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_llblAbout() As String
            Get
                Return ResourceManager.GetString("mainFrm_llblAbout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_llblSettings() As String
            Get
                Return ResourceManager.GetString("mainFrm_llblSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The number of copies to be printed.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_nudNCopieToolTip() As String
            Get
                Return ResourceManager.GetString("mainFrm_nudNCopieToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No printer selected.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_PrinterStatusLabel() As String
            Get
                Return ResourceManager.GetString("mainFrm_PrinterStatusLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save to file.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_PrinterStatusLabel_File() As String
            Get
                Return ResourceManager.GetString("mainFrm_PrinterStatusLabel_File", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export to PDF.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_PrinterStatusLabel_PDF() As String
            Get
                Return ResourceManager.GetString("mainFrm_PrinterStatusLabel_PDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to change printer settings.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_PrinterStatusLabelToolTip() As String
            Get
                Return ResourceManager.GetString("mainFrm_PrinterStatusLabelToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scan &amp;Multiple Pages.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_ScanMultiplePages() As String
            Get
                Return ResourceManager.GetString("mainFrm_ScanMultiplePages", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No scanner selected.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_ScannerstatusLabel() As String
            Get
                Return ResourceManager.GetString("mainFrm_ScannerstatusLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to select a different scanner.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_ScannerstatusLabelToolTip() As String
            Get
                Return ResourceManager.GetString("mainFrm_ScannerstatusLabelToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scan to &amp;File.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_ScanToFile() As String
            Get
                Return ResourceManager.GetString("mainFrm_ScanToFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Acquires an image and saves it to a specified file.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_ScanToFileToolTip() As String
            Get
                Return ResourceManager.GetString("mainFrm_ScanToFileToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New version available!.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_VersionStatusLabel() As String
            Get
                Return ResourceManager.GetString("mainFrm_VersionStatusLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click here to go to iCopy website and download the latest version.
        '''</summary>
        Friend Shared ReadOnly Property mainFrm_VersionStatusLabelToolTip() As String
            Get
                Return ResourceManager.GetString("mainFrm_VersionStatusLabelToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iCopy is already running. You can&apos;t run more than one instance of iCopy..
        '''</summary>
        Friend Shared ReadOnly Property Msg_AlreadyRunning() As String
            Get
                Return ResourceManager.GetString("Msg_AlreadyRunning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to cancel the operation? Click Yes if you are sure to proceed..
        '''</summary>
        Friend Shared ReadOnly Property Msg_CancelAcquisition() As String
            Get
                Return ResourceManager.GetString("Msg_CancelAcquisition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iCopy couldn&apos;t launch the predefined program for the following reason:
        '''
        '''{0}.
        '''</summary>
        Friend Shared ReadOnly Property Msg_CantOpenfile() As String
            Get
                Return ResourceManager.GetString("Msg_CantOpenfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have to chose a scanner. Click Yes to chose the scanner, or No to close iCopy..
        '''</summary>
        Friend Shared ReadOnly Property Msg_ChooseAScanner() As String
            Get
                Return ResourceManager.GetString("Msg_ChooseAScanner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not connect to the scanner, please wait for a while then click Retry..
        '''</summary>
        Friend Shared ReadOnly Property Msg_ConnectionError() As String
            Get
                Return ResourceManager.GetString("Msg_ConnectionError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection with the scanner lost. Please connect it to the computer and click Retry..
        '''</summary>
        Friend Shared ReadOnly Property Msg_ConnectionLost() As String
            Get
                Return ResourceManager.GetString("Msg_ConnectionLost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An exception occurred in your scanner driver. Please check if updates are available on the scanner manufacturer website, otherwise try to restart iCopy..
        '''</summary>
        Friend Shared ReadOnly Property Msg_DriverException() As String
            Get
                Return ResourceManager.GetString("Msg_DriverException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was an error in the scanner driver. Please make sure that the driver is updated and is compatible with your Windows version..
        '''</summary>
        Friend Shared ReadOnly Property Msg_ExceptionInDriver() As String
            Get
                Return ResourceManager.GetString("Msg_ExceptionInDriver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The file {0}
        '''already exists. Would you like to replace it?.
        '''</summary>
        Friend Shared ReadOnly Property Msg_FileAlreadyExists() As String
            Get
                Return ResourceManager.GetString("Msg_FileAlreadyExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iCopy can&apos;t write to file
        '''
        '''{0}
        '''
        '''Check that iCopy has write access to the path or that the file is not open..
        '''</summary>
        Friend Shared ReadOnly Property Msg_FileError() As String
            Get
                Return ResourceManager.GetString("Msg_FileError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert a number between {0} and {1}..
        '''</summary>
        Friend Shared ReadOnly Property Msg_InsertNumber() As String
            Get
                Return ResourceManager.GetString("Msg_InsertNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Some invalid command line parameters have been passed. Please check command line parameter syntax in README.txt..
        '''</summary>
        Friend Shared ReadOnly Property Msg_InvalidCommandLineParameters() As String
            Get
                Return ResourceManager.GetString("Msg_InvalidCommandLineParameters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language will be changed on next restart..
        '''</summary>
        Friend Shared ReadOnly Property Msg_Language() As String
            Get
                Return ResourceManager.GetString("Msg_Language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impossible to find License.txt in iCopy folder. Please make sure the file is in iCopy directory or read the license text here http://www.gnu.org/licenses/gpl.html (link copied to clipboard).
        '''</summary>
        Friend Shared ReadOnly Property Msg_LicenseFileNotFound() As String
            Get
                Return ResourceManager.GetString("Msg_LicenseFileNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No scanner connected, please connect a scanner and click Retry..
        '''</summary>
        Friend Shared ReadOnly Property Msg_NoScannerConnected() As String
            Get
                Return ResourceManager.GetString("Msg_NoScannerConnected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while setting resolution. Please try with another resolution and report this to iCopy bug tracker..
        '''</summary>
        Friend Shared ReadOnly Property Msg_ResolutionError() As String
            Get
                Return ResourceManager.GetString("Msg_ResolutionError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This resolution isn&apos;t available. Try with a different one..
        '''</summary>
        Friend Shared ReadOnly Property Msg_ResolutionUnavailable() As String
            Get
                Return ResourceManager.GetString("Msg_ResolutionUnavailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected scanner is currently used by another application. Please close the application and click Retry.
        '''</summary>
        Friend Shared ReadOnly Property Msg_ScannerInUse() As String
            Get
                Return ResourceManager.GetString("Msg_ScannerInUse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The scanner appears to be offline. Please try to plug the scanner again or to resume it from standby..
        '''</summary>
        Friend Shared ReadOnly Property Msg_ScannerOffline() As String
            Get
                Return ResourceManager.GetString("Msg_ScannerOffline", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The scanner is warming up. Please wait a minute, then try again..
        '''</summary>
        Friend Shared ReadOnly Property Msg_ScannerWarmingUp() As String
            Get
                Return ResourceManager.GetString("Msg_ScannerWarmingUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iCopy encountered an unhandled exception:
        '''
        '''{0}  
        '''
        '''We would greatly appreciate your help in making iCopy a better application. If you click OK, an error report file will be saved and you will be redirected to iCopy bug tracker. Please take the time to file a new bug and upload the generated file (its content has been copied to the Clipboard, you can also paste it in the bug report).
        '''
        '''Thank you for your support!.
        '''</summary>
        Friend Shared ReadOnly Property Msg_SendErrorReport2() As String
            Get
                Return ResourceManager.GetString("Msg_SendErrorReport2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iCopy must be run as administrator to register wiaaut.dll..
        '''</summary>
        Friend Shared ReadOnly Property Msg_UnauthorizedAccess() As String
            Get
                Return ResourceManager.GetString("Msg_UnauthorizedAccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred during acquisition. Please make sure that paper is loaded correctly in the right tray. Empty the document feeder if acquiring from flatbed and viceversa..
        '''</summary>
        Friend Shared ReadOnly Property Msg_UserIntervention() As String
            Get
                Return ResourceManager.GetString("Msg_UserIntervention", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please check that wiaaut.dll is located in iCopy directory.
        '''If it isn&apos;t, please download iCopy again..
        '''</summary>
        Friend Shared ReadOnly Property Msg_WiaautMissing() As String
            Get
                Return ResourceManager.GetString("Msg_WiaautMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iCopy has successfully registered WIA Automation Layer. Please restart iCopy..
        '''</summary>
        Friend Shared ReadOnly Property Msg_WIARegistrationSuccessful() As String
            Get
                Return ResourceManager.GetString("Msg_WIARegistrationSuccessful", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to It appears that some components needed by iCopy are not registered in your system.
        '''iCopy needs WIA Automation to be registered in order to work properly. 
        '''
        '''Click OK if you want iCopy to register wiaaut.dll for you, otherwise click Cancel to close iCopy. This operation requires administrator privileges..
        '''</summary>
        Friend Shared ReadOnly Property Msg_WIAUnregistered() As String
            Get
                Return ResourceManager.GetString("Msg_WIAUnregistered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property Msg_WIAUnregisteredCancel() As String
            Get
                Return ResourceManager.GetString("Msg_WIAUnregisteredCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iCopy needs to register a component.
        '''</summary>
        Friend Shared ReadOnly Property Msg_WIAUnregisteredInstruction() As String
            Get
                Return ResourceManager.GetString("Msg_WIAUnregisteredInstruction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog() As String
            Get
                Return ResourceManager.GetString("SettingsDialog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browse....
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_btnBrowseFile() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_btnBrowseFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browse....
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_btnBrowsePDF() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_btnBrowsePDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cancel.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_btnCancel() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_btnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;OK.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_btnOk() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_btnOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset to default.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_btnResetScanSettings() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_btnResetScanSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Default.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_btnResetSettings() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_btnResetSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset settings to their default values on next program restart.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_btnResetSettingsToolTip() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_btnResetSettingsToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set the BitDepth for Color mode. Modify this option only if you get problems with Auto..
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_cboBitDepthToolTip() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_cboBitDepthToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chose a language between the installed ones.
        '''To install a new language, download it from iCopy website and
        '''copy the folder xx-XX to iCopy folder.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_cboLanguageToolTip() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_cboLanguageToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open after acquisiton.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_chkOpenFile() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_chkOpenFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open after acquisiton.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_chkOpenPDF() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_chkOpenPDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remember image settings.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_chkRememberScanSettings() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_chkRememberScanSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If selected, iCopy will maintain image settings on next restart..
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_chkRememberScanSettingsToolTip() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_chkRememberScanSettingsToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remember window position after restart.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_chkRememberWindowPos() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_chkRememberWindowPos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If this option is enabled, iCopy window will be shown in the position it was when it was closed..
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_chkRememberWindowPosToolTip() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_chkRememberWindowPosToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check for updates.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_chkUpdates() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_chkUpdates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iCopy will check if a newer version is available for download, and will report it to the user. No information is sent. Requires an internet connection..
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_chkUpdatesToolTip() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_chkUpdatesToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Force Bit Depth for Color Mode.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_lblBitDepth() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_lblBitDepth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_lblLanguage() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_lblLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chose a language between the installed ones.
        '''To install a new language, download it from iCopy website and
        '''copy the folder xx-XX to iCopy folder.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_lblLanguageToolTip() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_lblLanguageToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NOTE Don&apos;t change the following setting unless you have problems with the acquired images.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_lblNote() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_lblNote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When saving to file:.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_lblSaveToFile() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_lblSaveToFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When saving to PDF:.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_lblSaveToPDF() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_lblSaveToPDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ask every time.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_rbAskFile() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_rbAskFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ask every time.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_rbAskPDF() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_rbAskPDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save to the following path.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_rbPathFile() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_rbPathFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save to the following path.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_rbPathPDF() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_rbPathPDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Settings.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_tabFileSettings() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_tabFileSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to General.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_tabGeneral() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_tabGeneral", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scanner Buttons.
        '''</summary>
        Friend Shared ReadOnly Property SettingsDialog_tabScannerButtons() As String
            Get
                Return ResourceManager.GetString("SettingsDialog_tabScannerButtons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} is loading
        '''Please wait....
        '''</summary>
        Friend Shared ReadOnly Property splashScreen_Loading() As String
            Get
                Return ResourceManager.GetString("splashScreen_Loading", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
