//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCopy.My.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iCopy.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate using PayPal.
        /// </summary>
        internal static string AboutBox_Donate {
            get {
                return ResourceManager.GetString("AboutBox_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is distributed under the terms of GNU GPL License..
        /// </summary>
        internal static string AboutBox_Label1 {
            get {
                return ResourceManager.GetString("AboutBox_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine your scanner and printer into a powerful photocopier..
        /// </summary>
        internal static string AboutBox_lblDescription {
            get {
                return ResourceManager.GetString("AboutBox_lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to read license text.
        /// </summary>
        internal static string AboutBox_LinkLabel3 {
            get {
                return ResourceManager.GetString("AboutBox_LinkLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; icopy.exe [/copy /file /multiplePages ..] [params]
        ///
        ///[params] are the parameters to be used. If a parameter is not specified, iCopy uses the values stored in settings
        ///
        ////copy /c				Directly copy from scanner to printer, using settings provided or default settings
        ////file /ScanToFile /f			Scan to a file. If file path is not provided a dialog will let you choose where to save the acquired image
        ////copyMultiplePages			Scan a multipage document. Also /copymultiplepages
        ////pdf				Scans to PDF. Output path can b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Console_Help {
            get {
                return ResourceManager.GetString("Console_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan More Pages.
        /// </summary>
        internal static string dlgScanMorePages {
            get {
                return ResourceManager.GetString("dlgScanMorePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Another Page.
        /// </summary>
        internal static string dlgScanMorePages_btnAddPage {
            get {
                return ResourceManager.GetString("dlgScanMorePages_btnAddPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scans another page with the current settings.
        /// </summary>
        internal static string dlgScanMorePages_btnAddPageToolTip {
            get {
                return ResourceManager.GetString("dlgScanMorePages_btnAddPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Pages.
        /// </summary>
        internal static string dlgScanMorePages_btnPrint {
            get {
                return ResourceManager.GetString("dlgScanMorePages_btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process the acquired images.
        /// </summary>
        internal static string dlgScanMorePages_btnPrintToolTip {
            get {
                return ResourceManager.GetString("dlgScanMorePages_btnPrintToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose if you want to add more pages or if you want to process the acquired pages..
        /// </summary>
        internal static string dlgScanMorePages_Label1 {
            get {
                return ResourceManager.GetString("dlgScanMorePages_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquired pages:.
        /// </summary>
        internal static string dlgScanMorePages_lblAcquiredPagesNText {
            get {
                return ResourceManager.GetString("dlgScanMorePages_lblAcquiredPagesNText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Settings.
        /// </summary>
        internal static string frmImageSettings {
            get {
                return ResourceManager.GetString("frmImageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string frmImageSettings_btnDefault {
            get {
                return ResourceManager.GetString("frmImageSettings_btnDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets image settings to their default values.
        /// </summary>
        internal static string frmImageSettings_btnDefaultToolTip {
            get {
                return ResourceManager.GetString("frmImageSettings_btnDefaultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select scanner resolution in DPI (dots per inch) higher values
        ///correspond to higher quality, but also longer acquisition time.
        ///Setting more than 1000 DPI will require a lot of extra time..
        /// </summary>
        internal static string frmImageSettings_cboResolutionToolTip {
            get {
                return ResourceManager.GetString("frmImageSettings_cboResolutionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center image.
        /// </summary>
        internal static string frmImageSettings_chkCenter {
            get {
                return ResourceManager.GetString("frmImageSettings_chkCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, iCopy prints the image in the center of the page, otherwise the image will be printed from the upper left corner..
        /// </summary>
        internal static string frmImageSettings_chkCenterToolTip {
            get {
                return ResourceManager.GetString("frmImageSettings_chkCenterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        internal static string frmImageSettings_lblBrightness {
            get {
                return ResourceManager.GetString("frmImageSettings_lblBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG Quality.
        /// </summary>
        internal static string frmImageSettings_lblCompressionLabel {
            get {
                return ResourceManager.GetString("frmImageSettings_lblCompressionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the Compression factor when saving to JPEG image using the Scan to Image function. The higher the value, the better the quality and the bigger the file size..
        /// </summary>
        internal static string frmImageSettings_lblCompressionLabelToolTip {
            get {
                return ResourceManager.GetString("frmImageSettings_lblCompressionLabelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        internal static string frmImageSettings_lblContrast {
            get {
                return ResourceManager.GetString("frmImageSettings_lblContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPI.
        /// </summary>
        internal static string frmImageSettings_lblDPI {
            get {
                return ResourceManager.GetString("frmImageSettings_lblDPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string frmImageSettings_lblPerc {
            get {
                return ResourceManager.GetString("frmImageSettings_lblPerc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        internal static string frmImageSettings_lblResolution {
            get {
                return ResourceManager.GetString("frmImageSettings_lblResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling.
        /// </summary>
        internal static string frmImageSettings_lblScaling {
            get {
                return ResourceManager.GetString("frmImageSettings_lblScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set brightness value..
        /// </summary>
        internal static string frmImageSettings_tbBrightnessToolTip {
            get {
                return ResourceManager.GetString("frmImageSettings_tbBrightnessToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set JPEG compression (Save to File only).
        /// </summary>
        internal static string frmImageSettings_tbCompressionToolTip {
            get {
                return ResourceManager.GetString("frmImageSettings_tbCompressionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set contrast value..
        /// </summary>
        internal static string frmImageSettings_tbContrastToolTip {
            get {
                return ResourceManager.GetString("frmImageSettings_tbContrastToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale the image to the selected percentage.
        /// </summary>
        internal static string frmImageSettings_tbScalingToolTip {
            get {
                return ResourceManager.GetString("frmImageSettings_tbScalingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set brightness value. Enter a value between -100 (darkest) and 100 (brightest).
        /// </summary>
        internal static string frmImageSettings_txtBrightnessToolTip {
            get {
                return ResourceManager.GetString("frmImageSettings_txtBrightnessToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set contrast value.  Enter a value from -100 (darker) to 100 (brighter).
        /// </summary>
        internal static string frmImageSettings_txtContrastToolTip {
            get {
                return ResourceManager.GetString("frmImageSettings_txtContrastToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the scaling percentage. Value must be between 1 and 200.
        /// </summary>
        internal static string frmImageSettings_txtScalingToolTip {
            get {
                return ResourceManager.GetString("frmImageSettings_txtScalingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start copy process (CTRL+S).
        /// </summary>
        internal static string mainFrm_btnCopyToolTip {
            get {
                return ResourceManager.GetString("mainFrm_btnCopyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Settings &gt;&gt;.
        /// </summary>
        internal static string mainFrm_btnImageSettings {
            get {
                return ResourceManager.GetString("mainFrm_btnImageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Settings &lt;&lt;.
        /// </summary>
        internal static string mainFrm_btnImageSettingsHide {
            get {
                return ResourceManager.GetString("mainFrm_btnImageSettingsHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows/Hides advanced image settings, which include
        ///Brightness, Contrast, Quality and Scaling (CTRL+I).
        /// </summary>
        internal static string mainFrm_btnImageSettingsToolTip {
            get {
                return ResourceManager.GetString("mainFrm_btnImageSettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Printer settings....
        /// </summary>
        internal static string mainFrm_btnPrintSetup {
            get {
                return ResourceManager.GetString("mainFrm_btnPrintSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change printer and printing options.
        /// </summary>
        internal static string mainFrm_btnPrintSetupToolTip {
            get {
                return ResourceManager.GetString("mainFrm_btnPrintSetupToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Scan Modes.
        /// </summary>
        internal static string mainFrm_btnScanModes {
            get {
                return ResourceManager.GetString("mainFrm_btnScanModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows other scan modes.
        /// </summary>
        internal static string mainFrm_btnScanModesToolTip {
            get {
                return ResourceManager.GetString("mainFrm_btnScanModesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose &amp;scanner....
        /// </summary>
        internal static string mainFrm_btnSelScanner {
            get {
                return ResourceManager.GetString("mainFrm_btnSelScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a dialog to choose a different scanner.
        /// </summary>
        internal static string mainFrm_btnSelScannerToolTip {
            get {
                return ResourceManager.GetString("mainFrm_btnSelScannerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings.
        /// </summary>
        internal static string mainFrm_btnSettings {
            get {
                return ResourceManager.GetString("mainFrm_btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string mainFrm_cboPrintModeItem0 {
            get {
                return ResourceManager.GetString("mainFrm_cboPrintModeItem0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black &amp; White.
        /// </summary>
        internal static string mainFrm_cboPrintModeItem1 {
            get {
                return ResourceManager.GetString("mainFrm_cboPrintModeItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set printing method.
        /// </summary>
        internal static string mainFrm_cboPrintModeToolTip {
            get {
                return ResourceManager.GetString("mainFrm_cboPrintModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string mainFrm_cboScanModeItem0 {
            get {
                return ResourceManager.GetString("mainFrm_cboScanModeItem0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grayscale.
        /// </summary>
        internal static string mainFrm_cboScanModeItem1 {
            get {
                return ResourceManager.GetString("mainFrm_cboScanModeItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string mainFrm_cboScanModeItem2 {
            get {
                return ResourceManager.GetString("mainFrm_cboScanModeItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the scanning method: 
        ///COLORS - Acquired image will be full-color, printing mode will be set to color automatically
        ///GRAYSCALE - Acquired image will be in grayscale. Scan will be faster. Printer automatically set to Black &amp; White
        ///TEXT - Acquired image will be black &amp; white. This is the fasted method, useful for text, books and copies.
        /// </summary>
        internal static string mainFrm_cboScanModeToolTip {
            get {
                return ResourceManager.GetString("mainFrm_cboScanModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Document Feeder (ADF).
        /// </summary>
        internal static string mainFrm_chkADF {
            get {
                return ResourceManager.GetString("mainFrm_chkADF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquire the pages using the Automatic Document Feeder..
        /// </summary>
        internal static string mainFrm_chkADFToolTip {
            get {
                return ResourceManager.GetString("mainFrm_chkADFToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplex acquisition.
        /// </summary>
        internal static string mainFrm_chkDuplex {
            get {
                return ResourceManager.GetString("mainFrm_chkDuplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used with ADF, tells the scanner to use duplex acquisition.
        /// </summary>
        internal static string mainFrm_chkDuplexToolTip {
            get {
                return ResourceManager.GetString("mainFrm_chkDuplexToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MULTIPAGE ACQUISITION (CTRL + M)
        ///iCopy will wait for the user to change the page on the flatbed (or ADF) to start another acquisition.
        ///You can scan several page at a time and print them all together or save them in a single PDF file..
        /// </summary>
        internal static string mainFrm_chkMultipageToolTip {
            get {
                return ResourceManager.GetString("mainFrm_chkMultipageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the output to PDF (CTRL +P).
        /// </summary>
        internal static string mainFrm_chkPDFToolTip {
            get {
                return ResourceManager.GetString("mainFrm_chkPDFToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string mainFrm_chkPreview {
            get {
                return ResourceManager.GetString("mainFrm_chkPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a dialog to select the area to be scanned.
        /// </summary>
        internal static string mainFrm_chkPreviewToolTip {
            get {
                return ResourceManager.GetString("mainFrm_chkPreviewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the image to a file (CTRL + F).
        /// </summary>
        internal static string mainFrm_chkSaveToFileToolTip {
            get {
                return ResourceManager.GetString("mainFrm_chkSaveToFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° of copies.
        /// </summary>
        internal static string mainFrm_lblCopies {
            get {
                return ResourceManager.GetString("mainFrm_lblCopies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Size.
        /// </summary>
        internal static string mainFrm_lblPaperSize {
            get {
                return ResourceManager.GetString("mainFrm_lblPaperSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        internal static string mainFrm_lblPrinter {
            get {
                return ResourceManager.GetString("mainFrm_lblPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner.
        /// </summary>
        internal static string mainFrm_lblScanner {
            get {
                return ResourceManager.GetString("mainFrm_lblScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About iCopy.
        /// </summary>
        internal static string mainFrm_llblAbout {
            get {
                return ResourceManager.GetString("mainFrm_llblAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string mainFrm_llblSettings {
            get {
                return ResourceManager.GetString("mainFrm_llblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of copies to be printed.
        /// </summary>
        internal static string mainFrm_nudNCopieToolTip {
            get {
                return ResourceManager.GetString("mainFrm_nudNCopieToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No printer selected.
        /// </summary>
        internal static string mainFrm_PrinterStatusLabel {
            get {
                return ResourceManager.GetString("mainFrm_PrinterStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to file.
        /// </summary>
        internal static string mainFrm_PrinterStatusLabel_File {
            get {
                return ResourceManager.GetString("mainFrm_PrinterStatusLabel_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to PDF.
        /// </summary>
        internal static string mainFrm_PrinterStatusLabel_PDF {
            get {
                return ResourceManager.GetString("mainFrm_PrinterStatusLabel_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to change printer settings.
        /// </summary>
        internal static string mainFrm_PrinterStatusLabelToolTip {
            get {
                return ResourceManager.GetString("mainFrm_PrinterStatusLabelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan &amp;Multiple Pages.
        /// </summary>
        internal static string mainFrm_ScanMultiplePages {
            get {
                return ResourceManager.GetString("mainFrm_ScanMultiplePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scanner selected.
        /// </summary>
        internal static string mainFrm_ScannerstatusLabel {
            get {
                return ResourceManager.GetString("mainFrm_ScannerstatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select a different scanner.
        /// </summary>
        internal static string mainFrm_ScannerstatusLabelToolTip {
            get {
                return ResourceManager.GetString("mainFrm_ScannerstatusLabelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan to &amp;File.
        /// </summary>
        internal static string mainFrm_ScanToFile {
            get {
                return ResourceManager.GetString("mainFrm_ScanToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquires an image and saves it to a specified file.
        /// </summary>
        internal static string mainFrm_ScanToFileToolTip {
            get {
                return ResourceManager.GetString("mainFrm_ScanToFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available!.
        /// </summary>
        internal static string mainFrm_VersionStatusLabel {
            get {
                return ResourceManager.GetString("mainFrm_VersionStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to go to iCopy website and download the latest version.
        /// </summary>
        internal static string mainFrm_VersionStatusLabelToolTip {
            get {
                return ResourceManager.GetString("mainFrm_VersionStatusLabelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iCopy is already running. You can&apos;t run more than one instance of iCopy..
        /// </summary>
        internal static string Msg_AlreadyRunning {
            get {
                return ResourceManager.GetString("Msg_AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the operation? Click Yes if you are sure to proceed..
        /// </summary>
        internal static string Msg_CancelAcquisition {
            get {
                return ResourceManager.GetString("Msg_CancelAcquisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iCopy couldn&apos;t launch the predefined program for the following reason:
        ///
        ///{0}.
        /// </summary>
        internal static string Msg_CantOpenfile {
            get {
                return ResourceManager.GetString("Msg_CantOpenfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to chose a scanner. Click Yes to chose the scanner, or No to close iCopy..
        /// </summary>
        internal static string Msg_ChooseAScanner {
            get {
                return ResourceManager.GetString("Msg_ChooseAScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the scanner, please wait for a while then click Retry..
        /// </summary>
        internal static string Msg_ConnectionError {
            get {
                return ResourceManager.GetString("Msg_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection with the scanner lost. Please connect it to the computer and click Retry..
        /// </summary>
        internal static string Msg_ConnectionLost {
            get {
                return ResourceManager.GetString("Msg_ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred in your scanner driver. Please check if updates are available on the scanner manufacturer website, otherwise try to restart iCopy..
        /// </summary>
        internal static string Msg_DriverException {
            get {
                return ResourceManager.GetString("Msg_DriverException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error in the scanner driver. Please make sure that the driver is updated and is compatible with your Windows version..
        /// </summary>
        internal static string Msg_ExceptionInDriver {
            get {
                return ResourceManager.GetString("Msg_ExceptionInDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0}
        ///already exists. Would you like to replace it?.
        /// </summary>
        internal static string Msg_FileAlreadyExists {
            get {
                return ResourceManager.GetString("Msg_FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iCopy can&apos;t write to file
        ///
        ///{0}
        ///
        ///Check that iCopy has write access to the path or that the file is not open..
        /// </summary>
        internal static string Msg_FileError {
            get {
                return ResourceManager.GetString("Msg_FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a number between {0} and {1}..
        /// </summary>
        internal static string Msg_InsertNumber {
            get {
                return ResourceManager.GetString("Msg_InsertNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some invalid command line parameters have been passed. Please check command line parameter syntax in README.txt..
        /// </summary>
        internal static string Msg_InvalidCommandLineParameters {
            get {
                return ResourceManager.GetString("Msg_InvalidCommandLineParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language will be changed on next restart..
        /// </summary>
        internal static string Msg_Language {
            get {
                return ResourceManager.GetString("Msg_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to find License.txt in iCopy folder. Please make sure the file is in iCopy directory or read the license text here http://www.gnu.org/licenses/gpl.html (link copied to clipboard).
        /// </summary>
        internal static string Msg_LicenseFileNotFound {
            get {
                return ResourceManager.GetString("Msg_LicenseFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scanner connected, please connect a scanner and click Retry..
        /// </summary>
        internal static string Msg_NoScannerConnected {
            get {
                return ResourceManager.GetString("Msg_NoScannerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while setting resolution. Please try with another resolution and report this to iCopy bug tracker..
        /// </summary>
        internal static string Msg_ResolutionError {
            get {
                return ResourceManager.GetString("Msg_ResolutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This resolution isn&apos;t available. Try with a different one..
        /// </summary>
        internal static string Msg_ResolutionUnavailable {
            get {
                return ResourceManager.GetString("Msg_ResolutionUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected scanner is currently used by another application. Please close the application and click Retry.
        /// </summary>
        internal static string Msg_ScannerInUse {
            get {
                return ResourceManager.GetString("Msg_ScannerInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scanner appears to be offline. Please try to plug the scanner again or to resume it from standby..
        /// </summary>
        internal static string Msg_ScannerOffline {
            get {
                return ResourceManager.GetString("Msg_ScannerOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scanner is warming up. Please wait a minute, then try again..
        /// </summary>
        internal static string Msg_ScannerWarmingUp {
            get {
                return ResourceManager.GetString("Msg_ScannerWarmingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iCopy encountered an unhandled exception:
        ///
        ///{0}  
        ///
        ///We would greatly appreciate your help in making iCopy a better application. If you click OK, an error report file will be saved and you will be redirected to iCopy bug tracker. Please take the time to file a new bug and upload the generated file (its content has been copied to the Clipboard, you can also paste it in the bug report).
        ///
        ///Thank you for your support!.
        /// </summary>
        internal static string Msg_SendErrorReport2 {
            get {
                return ResourceManager.GetString("Msg_SendErrorReport2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iCopy must be run as administrator to register wiaaut.dll..
        /// </summary>
        internal static string Msg_UnauthorizedAccess {
            get {
                return ResourceManager.GetString("Msg_UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during acquisition. Please make sure that paper is loaded correctly in the right tray. Empty the document feeder if acquiring from flatbed and viceversa..
        /// </summary>
        internal static string Msg_UserIntervention {
            get {
                return ResourceManager.GetString("Msg_UserIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check that wiaaut.dll is located in iCopy directory.
        ///If it isn&apos;t, please download iCopy again..
        /// </summary>
        internal static string Msg_WiaautMissing {
            get {
                return ResourceManager.GetString("Msg_WiaautMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iCopy has successfully registered WIA Automation Layer. Please restart iCopy..
        /// </summary>
        internal static string Msg_WIARegistrationSuccessful {
            get {
                return ResourceManager.GetString("Msg_WIARegistrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that some components needed by iCopy are not registered in your system.
        ///iCopy needs WIA Automation to be registered in order to work properly. 
        ///
        ///Click OK if you want iCopy to register wiaaut.dll for you, otherwise click Cancel to close iCopy. This operation requires administrator privileges..
        /// </summary>
        internal static string Msg_WIAUnregistered {
            get {
                return ResourceManager.GetString("Msg_WIAUnregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Msg_WIAUnregisteredCancel {
            get {
                return ResourceManager.GetString("Msg_WIAUnregisteredCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iCopy needs to register a component.
        /// </summary>
        internal static string Msg_WIAUnregisteredInstruction {
            get {
                return ResourceManager.GetString("Msg_WIAUnregisteredInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsDialog {
            get {
                return ResourceManager.GetString("SettingsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string SettingsDialog_btnBrowseFile {
            get {
                return ResourceManager.GetString("SettingsDialog_btnBrowseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string SettingsDialog_btnBrowsePDF {
            get {
                return ResourceManager.GetString("SettingsDialog_btnBrowsePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string SettingsDialog_btnCancel {
            get {
                return ResourceManager.GetString("SettingsDialog_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string SettingsDialog_btnOk {
            get {
                return ResourceManager.GetString("SettingsDialog_btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default.
        /// </summary>
        internal static string SettingsDialog_btnResetScanSettings {
            get {
                return ResourceManager.GetString("SettingsDialog_btnResetScanSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Default.
        /// </summary>
        internal static string SettingsDialog_btnResetSettings {
            get {
                return ResourceManager.GetString("SettingsDialog_btnResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings to their default values on next program restart.
        /// </summary>
        internal static string SettingsDialog_btnResetSettingsToolTip {
            get {
                return ResourceManager.GetString("SettingsDialog_btnResetSettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the BitDepth for Color mode. Modify this option only if you get problems with Auto..
        /// </summary>
        internal static string SettingsDialog_cboBitDepthToolTip {
            get {
                return ResourceManager.GetString("SettingsDialog_cboBitDepthToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose a language between the installed ones.
        ///To install a new language, download it from iCopy website and
        ///copy the folder xx-XX to iCopy folder.
        /// </summary>
        internal static string SettingsDialog_cboLanguageToolTip {
            get {
                return ResourceManager.GetString("SettingsDialog_cboLanguageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open after acquisiton.
        /// </summary>
        internal static string SettingsDialog_chkOpenFile {
            get {
                return ResourceManager.GetString("SettingsDialog_chkOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open after acquisiton.
        /// </summary>
        internal static string SettingsDialog_chkOpenPDF {
            get {
                return ResourceManager.GetString("SettingsDialog_chkOpenPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember image settings.
        /// </summary>
        internal static string SettingsDialog_chkRememberScanSettings {
            get {
                return ResourceManager.GetString("SettingsDialog_chkRememberScanSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If selected, iCopy will maintain image settings on next restart..
        /// </summary>
        internal static string SettingsDialog_chkRememberScanSettingsToolTip {
            get {
                return ResourceManager.GetString("SettingsDialog_chkRememberScanSettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember window position after restart.
        /// </summary>
        internal static string SettingsDialog_chkRememberWindowPos {
            get {
                return ResourceManager.GetString("SettingsDialog_chkRememberWindowPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this option is enabled, iCopy window will be shown in the position it was when it was closed..
        /// </summary>
        internal static string SettingsDialog_chkRememberWindowPosToolTip {
            get {
                return ResourceManager.GetString("SettingsDialog_chkRememberWindowPosToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string SettingsDialog_chkUpdates {
            get {
                return ResourceManager.GetString("SettingsDialog_chkUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iCopy will check if a newer version is available for download, and will report it to the user. No information is sent. Requires an internet connection..
        /// </summary>
        internal static string SettingsDialog_chkUpdatesToolTip {
            get {
                return ResourceManager.GetString("SettingsDialog_chkUpdatesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Bit Depth for Color Mode.
        /// </summary>
        internal static string SettingsDialog_lblBitDepth {
            get {
                return ResourceManager.GetString("SettingsDialog_lblBitDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsDialog_lblLanguage {
            get {
                return ResourceManager.GetString("SettingsDialog_lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose a language between the installed ones.
        ///To install a new language, download it from iCopy website and
        ///copy the folder xx-XX to iCopy folder.
        /// </summary>
        internal static string SettingsDialog_lblLanguageToolTip {
            get {
                return ResourceManager.GetString("SettingsDialog_lblLanguageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE Don&apos;t change the following setting unless you have problems with the acquired images.
        /// </summary>
        internal static string SettingsDialog_lblNote {
            get {
                return ResourceManager.GetString("SettingsDialog_lblNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When saving to file:.
        /// </summary>
        internal static string SettingsDialog_lblSaveToFile {
            get {
                return ResourceManager.GetString("SettingsDialog_lblSaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When saving to PDF:.
        /// </summary>
        internal static string SettingsDialog_lblSaveToPDF {
            get {
                return ResourceManager.GetString("SettingsDialog_lblSaveToPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask every time.
        /// </summary>
        internal static string SettingsDialog_rbAskFile {
            get {
                return ResourceManager.GetString("SettingsDialog_rbAskFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask every time.
        /// </summary>
        internal static string SettingsDialog_rbAskPDF {
            get {
                return ResourceManager.GetString("SettingsDialog_rbAskPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to the following path.
        /// </summary>
        internal static string SettingsDialog_rbPathFile {
            get {
                return ResourceManager.GetString("SettingsDialog_rbPathFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to the following path.
        /// </summary>
        internal static string SettingsDialog_rbPathPDF {
            get {
                return ResourceManager.GetString("SettingsDialog_rbPathPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Settings.
        /// </summary>
        internal static string SettingsDialog_tabFileSettings {
            get {
                return ResourceManager.GetString("SettingsDialog_tabFileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string SettingsDialog_tabGeneral {
            get {
                return ResourceManager.GetString("SettingsDialog_tabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner Buttons.
        /// </summary>
        internal static string SettingsDialog_tabScannerButtons {
            get {
                return ResourceManager.GetString("SettingsDialog_tabScannerButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is loading
        ///Please wait....
        /// </summary>
        internal static string splashScreen_Loading {
            get {
                return ResourceManager.GetString("splashScreen_Loading", resourceCulture);
            }
        }
    }
}
