//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCopy.Properties
{    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string DeviceID {
            get {
                return ((string)(this["DeviceID"]));
            }
            set {
                this["DeviceID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool PrintColor {
            get {
                return ((bool)(this["PrintColor"]));
            }
            set {
                this["PrintColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public global::System.Drawing.Point Location {
            get {
                return ((global::System.Drawing.Point)(this["Location"]));
            }
            set {
                this["Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool StoreLocation {
            get {
                return ((bool)(this["StoreLocation"]));
            }
            set {
                this["StoreLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Default)")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public global::System.Globalization.CultureInfo Culture {
            get {
                return ((global::System.Globalization.CultureInfo)(this["Culture"]));
            }
            set {
                this["Culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool RememberSettings {
            get {
                return ((bool)(this["RememberSettings"]));
            }
            set {
                this["RememberSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string DefaultPrinter {
            get {
                return ((string)(this["DefaultPrinter"]));
            }
            set {
                this["DefaultPrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string DefaultScanner {
            get {
                return ((string)(this["DefaultScanner"]));
            }
            set {
                this["DefaultScanner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A4")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string PrinterSize {
            get {
                return ((string)(this["PrinterSize"]));
            }
            set {
                this["PrinterSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool CustomCulture {
            get {
                return ((bool)(this["CustomCulture"]));
            }
            set {
                this["CustomCulture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public global::iCopy.ScanSettings LastScanSettings {
            get {
                return ((global::iCopy.ScanSettings)(this["LastScanSettings"]));
            }
            set {
                this["LastScanSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2011-01-01")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public global::System.DateTime LastVersionCheck {
            get {
                return ((global::System.DateTime)(this["LastVersionCheck"]));
            }
            set {
                this["LastVersionCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool CheckForUpdates {
            get {
                return ((bool)(this["CheckForUpdates"]));
            }
            set {
                this["CheckForUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool Silent {
            get {
                return ((bool)(this["Silent"]));
            }
            set {
                this["Silent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Center {
            get {
                return ((bool)(this["Center"]));
            }
            set {
                this["Center"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PDFAskWhereToSave {
            get {
                return ((bool)(this["PDFAskWhereToSave"]));
            }
            set {
                this["PDFAskWhereToSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PDFOpenAfterAcquisition {
            get {
                return ((bool)(this["PDFOpenAfterAcquisition"]));
            }
            set {
                this["PDFOpenAfterAcquisition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileOpenAfterAcquisition {
            get {
                return ((bool)(this["FileOpenAfterAcquisition"]));
            }
            set {
                this["FileOpenAfterAcquisition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileAskWhereToSave {
            get {
                return ((bool)(this["FileAskWhereToSave"]));
            }
            set {
                this["FileAskWhereToSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileSavePath {
            get {
                return ((string)(this["FileSavePath"]));
            }
            set {
                this["FileSavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PDFSavePath {
            get {
                return ((string)(this["PDFSavePath"]));
            }
            set {
                this["PDFSavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
       // [global::System.Configuration.SettingsProviderAttribute(typeof(iCopy.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public global::iCopy.ScanSettings DefaultScanSettings {
            get {
                return ((global::iCopy.ScanSettings)(this["DefaultScanSettings"]));
            }
            set {
                this["DefaultScanSettings"] = value;
            }
        }
    }
}
